#!/usr/bin/env python3
import subprocess
import os
from google.cloud import storage

from ai_saas.constants import IMG_DATA_DIR


db_path = '/tmp/test.db'
if os.path.exists(db_path):
    os.remove(db_path)

print(subprocess.check_output('redis-cli FLUSHALL', shell=True))

client = storage.Client()
bucket = client.bucket('fp-dev-bucket')
blobs = list(bucket.list_blobs(prefix=IMG_DATA_DIR))
bucket.delete_blobs(blobs)
