#!/usr/bin/env python3
import sys
import os

from ai_saas.lib.config import load_config


WSGI = '''
import sys
import os
sys.path.insert(0, '/home/fpu/code/')
os.environ['BASE_CODE_PATH'] = '/home/fpu/code'
os.environ['BASE_DATA_PATH'] = '/home/fpu/data'
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = '/home/fpu/code/fp/nocommit/google_app_creds.json'
from ai_saas.lib.server import build_server
from ai_saas.server.{label}.main import build
server = build_server('{label}', '{env}', build)
application = server.app
'''

APACHE = '''
<VirtualHost *:{port}>
    WSGIDaemonProcess fp user=fpu group=fpg threads=5
    WSGIScriptAlias / /var/www/fp/app.wsgi
    <Directory /home/fpu/code/fp>
        WSGIProcessGroup fp
        WSGIApplicationGroup %{{GLOBAL}}
        Require all granted
    </Directory>
</VirtualHost>
'''


def run(label, env):
    cfg = load_config(f'server/{label}', env)

    path = '/var/www/fp/app.wsgi'
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write(WSGI.format(
            label=label,
            env=env,
        ))

    path = '/etc/apache2/sites-available/fp.conf'
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write(APACHE.format(port=cfg.server.port))

    with open('/etc/apache2/ports.conf', 'w') as f:
        f.write(f'Listen {cfg.server.port}\n')


if __name__ == '__main__':
    run(sys.argv[1], sys.argv[2])
